if not WeakAuras.IsLibsOK() then return end

local AddonName = ...
local Private = select(2, ...)

Private.DiscordList = {
  [=[007bb]=],
  [=[AcidWeb]=],
  [=[aelen]=],
  [=[Aishuu]=],
  [=[Ariani  Continuity]=],
  [=[Ashaidrax]=],
  [=[Azortharion]=],
  [=[BadBrain]=],
  [=[Bart]=],
  [=[Boneshock]=],
  [=[Boxthor]=],
  [=[Burlis]=],
  [=[Causese]=],
  [=[Chab]=],
  [=[Darian]=],
  [=[Desik]=],
  [=[DjinnFish]=],
  [=[Dodgen]=],
  [=[Droodthor]=],
  [=[exality]=],
  [=[Fatpala]=],
  [=[Fels]=],
  [=[Fenchurch]=],
  [=[Fx]=],
  [=[Guffin]=],
  [=[Ifor]=],
  [=[Ipwnturkeys]=],
  [=[Ironi]=],
  [=[Jods]=],
  [=[kanegasi]=],
  [=[Koxy]=],
  [=[Leezy]=],
  [=[Listefano]=],
  [=[Luckyone]=],
  [=[Luxthos]=],
  [=[m33shoq]=],
  [=[Manabanana]=],
  [=[MetalMusicMan]=],
  [=[Murph]=],
  [=[Mynze]=],
  [=[Nona]=],
  [=[NostraDumAzz]=],
  [=[Oi]=],
  [=[Ora]=],
  [=[ParkSaeRoyi]=],
  [=[phoenix7700]=],
  [=[Raysur]=],
  [=[reggie]=],
  [=[Reloe]=],
  [=[Spaten]=],
  [=[Tel]=],
  [=[Tollo]=],
  [=[Translit]=],
  [=[update]=],
  [=[vozochris]=],
  [=[Wizeowel]=],
  [=[Xepheris]=],
}
Private.DiscordListCJ = {
}
Private.DiscordListK = {
}
