if not WeakAuras.IsLibsOK() then return end

local AddonName, Private = ...

Private.DiscordList = {
  [=[007bb]=],
  [=[AcidWeb]=],
  [=[aelen]=],
  [=[Aishuu]=],
  [=[Ariani  Continuity]=],
  [=[Azortharion]=],
  [=[BadBrain]=],
  [=[Bart]=],
  [=[Boneshock]=],
  [=[Boxthor]=],
  [=[Burlis]=],
  [=[Causese]=],
  [=[Chab]=],
  [=[cheswick]=],
  [=[Darian]=],
  [=[Desik]=],
  [=[DjinnFish]=],
  [=[exality]=],
  [=[Fatpala]=],
  [=[Fels]=],
  [=[Fenchurch]=],
  [=[Guffin]=],
  [=[Ifor]=],
  [=[Ironi]=],
  [=[Jiberish]=],
  [=[Jods]=],
  [=[kanegasi]=],
  [=[Koxy]=],
  [=[Listefano]=],
  [=[Luckyone]=],
  [=[Luxthos]=],
  [=[m33shoq]=],
  [=[maddin]=],
  [=[Max rdv 2026 pour TBC cla]=],
  [=[MetalMusicMan]=],
  [=[Murph]=],
  [=[Mynze]=],
  [=[Nona]=],
  [=[NostraDumAzz]=],
  [=[Ocelots]=],
  [=[Oi]=],
  [=[Ora]=],
  [=[phoenix7700]=],
  [=[Pseiko]=],
  [=[Reloe]=],
  [=[Shwinsta]=],
  [=[Slurp]=],
  [=[Spaten]=],
  [=[Tollo]=],
  [=[update]=],
  [=[vozochris]=],
  [=[Wizeowel]=],
  [=[Xepheris]=],
  [=[Мектран]=],
}
Private.DiscordListCJ = {
}
Private.DiscordListK = {
}
