local Cvar =
{
	Name = "CVar",
	Type = "System",
	Namespace = "CVar",

	Functions =
	{
		{
			Name = "GetCVar",
			Type = "Function",

			Arguments =
			{
				{ Name = "cvar", Type = "string", Nilable = false },
			},

			Returns =
			{
				{ Name = "string", Type = "string", Nilable = false },
			},
		},
		{
			Name = "GetCVarAbsoluteMin",
			Type = "Function",

			Arguments =
			{
				{ Name = "cvar", Type = "string", Nilable = false },
			},

			Returns =
			{
				{ Name = "min", Type = "number", Nilable = false },
			},
		},
		{
			Name = "GetCVarBool",
			Type = "Function",

			Arguments =
			{
				{ Name = "cvar", Type = "string", Nilable = false },
			},

			Returns =
			{
				{ Name = "value", Type = "bool", Nilable = false },
			},
		},
		{
			Name = "GetCVarDefault",
			Type = "Function",

			Arguments =
			{
				{ Name = "CVar", Type = "string", Nilable = false },
			},

			Returns =
			{
				{ Name = "value", Type = "string", Nilable = false },
			},
		},
		{
			Name = "GetCVarInfo",
			Type = "Function",

			Arguments =
			{
				{ Name = "cvar", Type = "string", Nilable = false },
			},

			Returns =
			{
				{ Name = "value", Type = "string", Nilable = false },
				{ Name = "defaultValue", Type = "string", Nilable = false },
				{ Name = "serverStoredAccountWide", Type = "bool", Nilable = false },
				{ Name = "serverStoredPerCharacter", Type = "bool", Nilable = false },
			},
		},
		{
			Name = "GetCVarMin",
			Type = "Function",

			Arguments =
			{
				{ Name = "cvar", Type = "string", Nilable = false },
			},

			Returns =
			{
				{ Name = "min", Type = "number", Nilable = false },
			},
		},
		{
			Name = "RegisterCVar",
			Type = "Function",

			Arguments =
			{
				{ Name = "cvar", Type = "string", Nilable = false },
				{ Name = "default", Type = "string", Nilable = false },
			},

		},
		{
			Name = "SetCVar",
			Type = "Function",

			Arguments =
			{
				{ Name = "cvar", Type = "string", Nilable = false },
				{ Name = "value", Type = "any", Nilable = false },
				{ Name = "raiseEvent", Type = "string", Nilable = true },
			},

		},
		{
			Name = "GetCVarAbsoluteMax",
			Type = "Function",
		},
		{
			Name = "GetCVarMax",
			Type = "Function",
		},
	},

	CVars =
	{
		{ Name = "accountList", Type = "CVar", DefaultValue = "", Category = "General" },
		{ Name = "accountName", Type = "CVar", DefaultValue = "", Category = "General" },
		{ Name = "accounttype", Type = "CVar", DefaultValue = "", Category = "General" },
		{ Name = "advancedWatchFrame", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "advancedWorldMap", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "AllowMultisampleFBO", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "alwaysCompareItems", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "alwaysShowActionBars", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "assistAttack", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "asyncHandlerTimeout", Type = "CVar", DefaultValue = "100", Category = "General" },
		{ Name = "asyncThreadSleep", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "auctionDisplayOnCharacter", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "autoClearAFK", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "autoCompleteResortNamesOnRecency", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "autoCompleteUseContext", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "autoCompleteWhenEditingFromCenter", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "autoDismount", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "autoDismountFlying", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "autoFilledMultiCastSlots", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "autoInteract", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "autojoinBGVoice", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "autojoinPartyVoice", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "autoLootDefault", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "autoQuestProgress", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "autoQuestWatch", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "autoRangedCombat", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "autoSelfCast", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "autoStand", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "autoUnshift", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "baseMip", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "blockTrades", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "BlockTrades", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "bspcache", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "buffDurations", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "calendarShowBattlegrounds", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "calendarShowDarkmoon", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "calendarShowLockouts", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "calendarShowResets", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "calendarShowWeeklyHolidays", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "cameraBobbing", Type = "CVar", DefaultValue = "0", Category = "Camera" },
		{ Name = "cameraBobbingSmoothSpeed", Type = "CVar", DefaultValue = "0.8", Category = "Camera" },
		{ Name = "cameraCustomViewSmoothing", Type = "CVar", DefaultValue = "0", Category = "Camera" },
		{ Name = "cameraDistanceMax", Type = "CVar", DefaultValue = "15.0", Category = "Camera" },
		{ Name = "cameraDistanceMaxFactor", Type = "CVar", DefaultValue = "1.0", Category = "Camera" },
		{ Name = "cameraDistanceMoveSpeed", Type = "CVar", DefaultValue = "8.33", Category = "Camera" },
		{ Name = "cameraDistanceSmoothSpeed", Type = "CVar", DefaultValue = "8.33", Category = "Camera" },
		{ Name = "cameraDive", Type = "CVar", DefaultValue = "1", Category = "Camera" },
		{ Name = "cameraFlyingMountHeightSmoothSpeed", Type = "CVar", DefaultValue = "2.0", Category = "Camera" },
		{ Name = "cameraFoVSmoothSpeed", Type = "CVar", DefaultValue = "0.5", Category = "Camera" },
		{ Name = "cameraGroundSmoothSpeed", Type = "CVar", DefaultValue = "7.5", Category = "Camera" },
		{ Name = "cameraHeightIgnoreStandState", Type = "CVar", DefaultValue = "0", Category = "Camera" },
		{ Name = "cameraHeightSmoothSpeed", Type = "CVar", DefaultValue = "1.2", Category = "Camera" },
		{ Name = "cameraPitchMoveSpeed", Type = "CVar", DefaultValue = "90", Category = "Camera" },
		{ Name = "cameraPitchSmoothMax", Type = "CVar", DefaultValue = "30.0", Category = "Camera" },
		{ Name = "cameraPitchSmoothMin", Type = "CVar", DefaultValue = "0.0", Category = "Camera" },
		{ Name = "cameraPitchSmoothSpeed", Type = "CVar", DefaultValue = "45", Category = "Camera" },
		{ Name = "cameraPivot", Type = "CVar", DefaultValue = "1", Category = "Camera" },
		{ Name = "cameraPivotDXMax", Type = "CVar", DefaultValue = "0.05", Category = "Camera" },
		{ Name = "cameraPivotDYMin", Type = "CVar", DefaultValue = "0.00", Category = "Camera" },
		{ Name = "cameraSavedDistance", Type = "CVar", DefaultValue = "5.55", Category = "Camera" },
		{ Name = "cameraSavedPitch", Type = "CVar", DefaultValue = "10.0", Category = "Camera" },
		{ Name = "cameraSavedVehicleDistance", Type = "CVar", DefaultValue = "-1.0", Category = "Camera" },
		{ Name = "camerasmooth", Type = "CVar", DefaultValue = "1", Category = "Camera" },
		{ Name = "cameraSmooth", Type = "CVar", DefaultValue = "1", Category = "Camera" },
		{ Name = "cameraSmoothPitch", Type = "CVar", DefaultValue = "1", Category = "Camera" },
		{ Name = "cameraSmoothStyle", Type = "CVar", DefaultValue = "4", Category = "Camera" },
		{ Name = "cameraSmoothTimeMax", Type = "CVar", DefaultValue = "2.0", Category = "Camera" },
		{ Name = "cameraSmoothTimeMin", Type = "CVar", DefaultValue = "0.1", Category = "Camera" },
		{ Name = "cameraSmoothTrackingStyle", Type = "CVar", DefaultValue = "4", Category = "Camera" },
		{ Name = "cameraSmoothYaw", Type = "CVar", DefaultValue = "1", Category = "Camera" },
		{ Name = "cameraSubmergeFinalPitch", Type = "CVar", DefaultValue = "5.0", Category = "Camera" },
		{ Name = "cameraSubmergePitch", Type = "CVar", DefaultValue = "18.0", Category = "Camera" },
		{ Name = "cameraSurfaceFinalPitch", Type = "CVar", DefaultValue = "5.0", Category = "Camera" },
		{ Name = "cameraSurfacePitch", Type = "CVar", DefaultValue = "0.0", Category = "Camera" },
		{ Name = "cameraTargetSmoothSpeed", Type = "CVar", DefaultValue = "90", Category = "Camera" },
		{ Name = "cameraTerrainTilt", Type = "CVar", DefaultValue = "0", Category = "Camera" },
		{ Name = "cameraTerrainTiltTimeMax", Type = "CVar", DefaultValue = "10.0", Category = "Camera" },
		{ Name = "cameraTerrainTiltTimeMin", Type = "CVar", DefaultValue = "3.0", Category = "Camera" },
		{ Name = "cameraView", Type = "CVar", DefaultValue = "2", Category = "Camera" },
		{ Name = "cameraViewBlendStyle", Type = "CVar", DefaultValue = "1", Category = "Camera" },
		{ Name = "cameraWaterCollision", Type = "CVar", DefaultValue = "1", Category = "Camera" },
		{ Name = "cameraYawMoveSpeed", Type = "CVar", DefaultValue = "180", Category = "Camera" },
		{ Name = "cameraYawSmoothMax", Type = "CVar", DefaultValue = "0.0", Category = "Camera" },
		{ Name = "cameraYawSmoothMin", Type = "CVar", DefaultValue = "0.0", Category = "Camera" },
		{ Name = "cameraYawSmoothSpeed", Type = "CVar", DefaultValue = "180", Category = "Camera" },
		{ Name = "ChatAmbienceVolume", Type = "CVar", DefaultValue = "0.3", Category = "Chat" },
		{ Name = "chatBubbles", Type = "CVar", DefaultValue = "1", Category = "Chat" },
		{ Name = "chatBubblesParty", Type = "CVar", DefaultValue = "1", Category = "Chat" },
		{ Name = "chatLocked", Type = "CVar", DefaultValue = "0", Category = "Chat" },
		{ Name = "ChatMusicVolume", Type = "CVar", DefaultValue = "0.3", Category = "Chat" },
		{ Name = "ChatSoundVolume", Type = "CVar", DefaultValue = "0.4", Category = "Chat" },
		{ Name = "checkAddonVersion", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "CinematicJoystick", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "colorblindMode", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "colorChatNamesByClass", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "CombatDamage", Type = "CVar", DefaultValue = "1", Category = "Combat" },
		{ Name = "CombatHealing", Type = "CVar", DefaultValue = "1", Category = "Combat" },
		{ Name = "combatLogOn", Type = "CVar", DefaultValue = "1", Category = "Combat" },
		{ Name = "CombatLogPeriodicSpells", Type = "CVar", DefaultValue = "1", Category = "Combat" },
		{ Name = "combatLogRetentionTime", Type = "CVar", DefaultValue = "300", Category = "Combat" },
		{ Name = "combatTextFloatMode", Type = "CVar", DefaultValue = "1", Category = "Combat" },
		{ Name = "componentCompress", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "componentTextureLevel", Type = "CVar", DefaultValue = "8", Category = "General" },
		{ Name = "componentThread", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "consolidateBuffs", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "dbCompress", Type = "CVar", DefaultValue = "-1", Category = "General" },
		{ Name = "decorateAccountName", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "deselectOnClick", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "DesktopGamma", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "displayFreeBagSlots", Type = "CVar", DefaultValue = "0", Category = "Interface" },
		{ Name = "displayWorldPVPObjectives", Type = "CVar", DefaultValue = "1", Category = "Interface" },
		{ Name = "dontShowEquipmentSetsOnItems", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "enableCombatText", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "EnableMicrophone", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "EnableMultiTouch", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "enablePVPNotifyAFK", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "EnableVoiceChat", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "enableWowMouse", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "environmentDetail", Type = "CVar", DefaultValue = "1.0", Category = "General" },
		{ Name = "equipmentManager", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "ErrorFilter", Type = "CVar", DefaultValue = "all", Category = "General" },
		{ Name = "ErrorLevelMax", Type = "CVar", DefaultValue = "3", Category = "General" },
		{ Name = "ErrorLevelMin", Type = "CVar", DefaultValue = "2", Category = "General" },
		{ Name = "errors", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "Errors", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "ERRORS", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "expansionMovie", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "extShadowQuality", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "farclip", Type = "CVar", DefaultValue = "350", Category = "General" },
		{ Name = "farClipOverride", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "fctAllSpellMechanics", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "fctAuras", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "fctCombatState", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "fctComboPoints", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "fctDamageReduction", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "fctDodgeParryMiss", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "fctEnergyGains", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "fctFriendlyHealers", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "fctHonorGains", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "fctLowManaHealth", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "fctPeriodicEnergyGains", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "fctReactives", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "fctRepChanges", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "fctSpellMechanics", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "fctSpellMechanicsOther", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "ffxDeath", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "FFXDeath", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "ffxGlow", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "FFXGlow", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "ffxNetherWorld", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "ffxRectangle", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "ffxSpecial", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "fixedFunction", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "FixVBOBug", Type = "CVar", DefaultValue = "-1", Category = "General" },
		{ Name = "flaggedTutorials", Type = "CVar", DefaultValue = "", Category = "General" },
		{ Name = "footstepBias", Type = "CVar", DefaultValue = "0.125", Category = "General" },
		{ Name = "FootstepSounds", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "forceEnglishNames", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "fullSizeFocusFrame", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "g_accountUsesToken", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "gameTip", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "gamma", Type = "CVar", DefaultValue = "1.0", Category = "General" },
		{ Name = "Gamma", Type = "CVar", DefaultValue = "1.0", Category = "General" },
		{ Name = "GLFaster", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "groundEffectDensity", Type = "CVar", DefaultValue = "16", Category = "General" },
		{ Name = "groundEffectDist", Type = "CVar", DefaultValue = "70.0", Category = "General" },
		{ Name = "guildMemberNotify", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "guildRecruitmentChannel", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "guildShowOffline", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "gxApi", Type = "CVar", DefaultValue = "OpenGL", Category = "Graphics" },
		{ Name = "gxAspect", Type = "CVar", DefaultValue = "1", Category = "Graphics" },
		{ Name = "gxColorBits", Type = "CVar", DefaultValue = "24", Category = "Graphics" },
		{ Name = "gxCursor", Type = "CVar", DefaultValue = "1", Category = "Graphics" },
		{ Name = "gxDepthBits", Type = "CVar", DefaultValue = "24", Category = "Graphics" },
		{ Name = "gxFixLag", Type = "CVar", DefaultValue = "1", Category = "Graphics" },
		{ Name = "gxMaximize", Type = "CVar", DefaultValue = "0", Category = "Graphics" },
		{ Name = "gxMultisample", Type = "CVar", DefaultValue = "1", Category = "Graphics" },
		{ Name = "gxMultisampleQuality", Type = "CVar", DefaultValue = "0.0", Category = "Graphics" },
		{ Name = "gxoverride", Type = "CVar", DefaultValue = "", Category = "Graphics" },
		{ Name = "gxOverride", Type = "CVar", DefaultValue = "", Category = "Graphics" },
		{ Name = "gxRefresh", Type = "CVar", DefaultValue = "75", Category = "Graphics" },
		{ Name = "gxResolution", Type = "CVar", DefaultValue = "1440x900", Category = "Graphics" },
		{ Name = "gxStereoConvergence", Type = "CVar", DefaultValue = "1", Category = "Graphics" },
		{ Name = "gxStereoEnabled", Type = "CVar", DefaultValue = "0", Category = "Graphics" },
		{ Name = "gxStereoSeparation", Type = "CVar", DefaultValue = "25", Category = "Graphics" },
		{ Name = "gxTextureCacheSize", Type = "CVar", DefaultValue = "0", Category = "Graphics" },
		{ Name = "gxTripleBuffer", Type = "CVar", DefaultValue = "0", Category = "Graphics" },
		{ Name = "gxVSync", Type = "CVar", DefaultValue = "1", Category = "Graphics" },
		{ Name = "gxWindow", Type = "CVar", DefaultValue = "0", Category = "Graphics" },
		{ Name = "heapAllocTracking", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "hidePartyInRaid", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "horizonFarclipScale", Type = "CVar", DefaultValue = "4.0", Category = "General" },
		{ Name = "horizonNearclipScale", Type = "CVar", DefaultValue = "0.7", Category = "General" },
		{ Name = "hwdetect", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "hwDetect", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "hwPCF", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "InboundChatVolume", Type = "CVar", DefaultValue = "1.0", Category = "General" },
		{ Name = "iTunesRemoteFeedback", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "iTunesTrackDisplay", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "joystick", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "Joystick", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "JOYSTICK", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "lastCharacterIndex", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "lastTalkedToGM", Type = "CVar", DefaultValue = "", Category = "General" },
		{ Name = "lfdCollapsedHeaders", Type = "CVar", DefaultValue = "", Category = "General" },
		{ Name = "lfdSelectedDungeons", Type = "CVar", DefaultValue = "", Category = "General" },
		{ Name = "lfgAutoFill", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "lfgAutoJoin", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "lfgSelectedRoles", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "locale", Type = "CVar", DefaultValue = "****", Category = "General" },
		{ Name = "lockActionBars", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "lootUnderMouse", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "mapObjLightLOD", Type = "CVar", DefaultValue = "0", Category = "Map" },
		{ Name = "mapQuestDifficulty", Type = "CVar", DefaultValue = "0", Category = "Map" },
		{ Name = "mapShadows", Type = "CVar", DefaultValue = "1", Category = "Map" },
		{ Name = "maxFPS", Type = "CVar", DefaultValue = "200", Category = "General" },
		{ Name = "maxFPSBk", Type = "CVar", DefaultValue = "30", Category = "General" },
		{ Name = "MaxLights", Type = "CVar", DefaultValue = "4", Category = "General" },
		{ Name = "minimapInsideZoom", Type = "CVar", DefaultValue = "3", Category = "Map" },
		{ Name = "minimapPortalMax", Type = "CVar", DefaultValue = "99", Category = "Map" },
		{ Name = "minimapTrackedInfo", Type = "CVar", DefaultValue = "", Category = "Map" },
		{ Name = "minimapZoom", Type = "CVar", DefaultValue = "3", Category = "Map" },
		{ Name = "miniWorldMap", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "mouseInvertPitch", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "mouseInvertYaw", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "mouseSpeed", Type = "CVar", DefaultValue = "1.0", Category = "General" },
		{ Name = "movie", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "MovieRecordingAutoCompress", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "MovieRecordingCompression", Type = "CVar", DefaultValue = "1635148593", Category = "General" },
		{ Name = "MovieRecordingCursor", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "MovieRecordingForceEnable", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "MovieRecordingFramerate", Type = "CVar", DefaultValue = "29.97", Category = "General" },
		{ Name = "MovieRecordingGetTexImage", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "MovieRecordingGUI", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "MovieRecordingIcon", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "MovieRecordingPath", Type = "CVar", DefaultValue = "", Category = "General" },
		{ Name = "MovieRecordingQuality", Type = "CVar", DefaultValue = "2", Category = "General" },
		{ Name = "movierecordingrecover", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "MovieRecordingRecover", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "MovieRecordingSound", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "MovieRecordingWidth", Type = "CVar", DefaultValue = "640", Category = "General" },
		{ Name = "movieSubtitle", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "MultiTouchAutoRunInvertY", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "MultiTouchAutoRunSensitivityX", Type = "CVar", DefaultValue = "8", Category = "General" },
		{ Name = "MultiTouchAutoRunSensitivityY", Type = "CVar", DefaultValue = "9", Category = "General" },
		{ Name = "nameplateAllowOverlap", Type = "CVar", DefaultValue = "1", Category = "Nameplates" },
		{ Name = "nameplateShowEnemies", Type = "CVar", DefaultValue = "0", Category = "Nameplates" },
		{ Name = "nameplateShowEnemyGuardians", Type = "CVar", DefaultValue = "1", Category = "Nameplates" },
		{ Name = "nameplateShowEnemyPets", Type = "CVar", DefaultValue = "1", Category = "Nameplates" },
		{ Name = "nameplateShowEnemyTotems", Type = "CVar", DefaultValue = "1", Category = "Nameplates" },
		{ Name = "nameplateShowFriendlyGuardians", Type = "CVar", DefaultValue = "1", Category = "Nameplates" },
		{ Name = "nameplateShowFriendlyPets", Type = "CVar", DefaultValue = "1", Category = "Nameplates" },
		{ Name = "nameplateShowFriendlyTotems", Type = "CVar", DefaultValue = "1", Category = "Nameplates" },
		{ Name = "nameplateShowFriends", Type = "CVar", DefaultValue = "0", Category = "Nameplates" },
		{ Name = "nearclip", Type = "CVar", DefaultValue = "0.2", Category = "General" },
		{ Name = "NvidiaViewportFix", Type = "CVar", DefaultValue = "-1", Category = "General" },
		{ Name = "objectFade", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "objectFadeZFill", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "ObjectSelectionCircle", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "occlusion", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "OutboundChatVolume", Type = "CVar", DefaultValue = "1.0", Category = "General" },
		{ Name = "particleDensity", Type = "CVar", DefaultValue = "1.0", Category = "General" },
		{ Name = "partyBackgroundOpacity", Type = "CVar", DefaultValue = "0.5", Category = "General" },
		{ Name = "partyStatusText", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "pathDistTol", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "PetMeleeDamage", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "PetSpellDamage", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "petStatusText", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "playerStatLeftDropdown", Type = "CVar", DefaultValue = "", Category = "General" },
		{ Name = "playerStatRightDropdown", Type = "CVar", DefaultValue = "", Category = "General" },
		{ Name = "playerStatusText", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "POIShiftComplete", Type = "CVar", DefaultValue = "0.6", Category = "General" },
		{ Name = "portal", Type = "CVar", DefaultValue = "us", Category = "General" },
		{ Name = "predictedHealth", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "predictedPower", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "preferredFullscreenMode", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "previewTalents", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "processAffinityMask", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "profanityFilter", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "projectedTextures", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "PushToTalkButton", Type = "CVar", DefaultValue = "`", Category = "General" },
		{ Name = "PushToTalkSound", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "questFadingDisable", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "questLogCollapseFilter", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "questPOI", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "readContest", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "readEULA", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "readScanning", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "readTerminationWithoutNotice", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "readTOS", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "realmList", Type = "CVar", DefaultValue = "us.logon.worldofwarcraft.com:3724", Category = "General" },
		{ Name = "realmlistbn", Type = "CVar", DefaultValue = "", Category = "General" },
		{ Name = "realmListbn", Type = "CVar", DefaultValue = "", Category = "General" },
		{ Name = "realmName", Type = "CVar", DefaultValue = "", Category = "General" },
		{ Name = "removeChatDelay", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "rotateMinimap", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "screenEdgeFlash", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "screenshotFormat", Type = "CVar", DefaultValue = "jpeg", Category = "General" },
		{ Name = "screenshotQuality", Type = "CVar", DefaultValue = "3", Category = "General" },
		{ Name = "scriptErrors", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "scriptProfile", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "secureAbilityToggle", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "serverAlert", Type = "CVar", DefaultValue = "SERVER_ALERT_URL", Category = "General" },
		{ Name = "serviceTypeFilter", Type = "CVar", DefaultValue = "3", Category = "General" },
		{ Name = "shadowCull", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "shadowInstancing", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "shadowLevel", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "shadowLOD", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "shadowScissor", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "ShowAllSpellRanks", Type = "CVar", DefaultValue = "1", Category = "Interface" },
		{ Name = "showArenaEnemyCastbar", Type = "CVar", DefaultValue = "1", Category = "Interface" },
		{ Name = "showArenaEnemyFrames", Type = "CVar", DefaultValue = "1", Category = "Interface" },
		{ Name = "showArenaEnemyPets", Type = "CVar", DefaultValue = "1", Category = "Interface" },
		{ Name = "showBattlefieldMinimap", Type = "CVar", DefaultValue = "0", Category = "Interface" },
		{ Name = "showCastableBuffs", Type = "CVar", DefaultValue = "0", Category = "Interface" },
		{ Name = "showCastableDebuffs", Type = "CVar", DefaultValue = "0", Category = "Interface" },
		{ Name = "showChatIcons", Type = "CVar", DefaultValue = "0", Category = "Interface" },
		{ Name = "ShowClassColorInNameplate", Type = "CVar", DefaultValue = "0", Category = "Interface" },
		{ Name = "showClock", Type = "CVar", DefaultValue = "1", Category = "Interface" },
		{ Name = "showDispelDebuffs", Type = "CVar", DefaultValue = "0", Category = "Interface" },
		{ Name = "ShowErrors", Type = "CVar", DefaultValue = "1", Category = "Interface" },
		{ Name = "showfootprintparticles", Type = "CVar", DefaultValue = "1", Category = "Interface" },
		{ Name = "showfootprints", Type = "CVar", DefaultValue = "1", Category = "Interface" },
		{ Name = "showGameTips", Type = "CVar", DefaultValue = "1", Category = "Interface" },
		{ Name = "showItemLevel", Type = "CVar", DefaultValue = "0", Category = "Interface" },
		{ Name = "showKeyring", Type = "CVar", DefaultValue = "0", Category = "Interface" },
		{ Name = "showLootSpam", Type = "CVar", DefaultValue = "1", Category = "Interface" },
		{ Name = "showNewbieTips", Type = "CVar", DefaultValue = "1", Category = "Interface" },
		{ Name = "showPartyBackground", Type = "CVar", DefaultValue = "0", Category = "Interface" },
		{ Name = "showPartyPets", Type = "CVar", DefaultValue = "1", Category = "Interface" },
		{ Name = "showQuestObjectivesOnMap", Type = "CVar", DefaultValue = "1", Category = "Interface" },
		{ Name = "showQuestTrackingTooltips", Type = "CVar", DefaultValue = "1", Category = "Interface" },
		{ Name = "showRaidRange", Type = "CVar", DefaultValue = "0", Category = "Interface" },
		{ Name = "showTargetCastbar", Type = "CVar", DefaultValue = "1", Category = "Interface" },
		{ Name = "showTargetOfTarget", Type = "CVar", DefaultValue = "0", Category = "Interface" },
		{ Name = "showTokenFrame", Type = "CVar", DefaultValue = "0", Category = "Interface" },
		{ Name = "showTokenFrameHonor", Type = "CVar", DefaultValue = "0", Category = "Interface" },
		{ Name = "showToolsUI", Type = "CVar", DefaultValue = "-1", Category = "Interface" },
		{ Name = "showTutorials", Type = "CVar", DefaultValue = "1", Category = "Interface" },
		{ Name = "showVKeyCastbar", Type = "CVar", DefaultValue = "1", Category = "Interface" },
		{ Name = "SkyCloudLOD", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "Sound_AmbienceVolume", Type = "CVar", DefaultValue = "0.6", Category = "Sound" },
		{ Name = "Sound_DSPBufferSize", Type = "CVar", DefaultValue = "0", Category = "Sound" },
		{ Name = "Sound_EnableAllSound", Type = "CVar", DefaultValue = "1", Category = "Sound" },
		{ Name = "Sound_EnableAmbience", Type = "CVar", DefaultValue = "1", Category = "Sound" },
		{ Name = "Sound_EnableArmorFoleySoundForOthers", Type = "CVar", DefaultValue = "1", Category = "Sound" },
		{ Name = "Sound_EnableArmorFoleySoundForSelf", Type = "CVar", DefaultValue = "1", Category = "Sound" },
		{ Name = "Sound_EnableDSPEffects", Type = "CVar", DefaultValue = "1", Category = "Sound" },
		{ Name = "Sound_EnableEmoteSounds", Type = "CVar", DefaultValue = "1", Category = "Sound" },
		{ Name = "Sound_EnableErrorSpeech", Type = "CVar", DefaultValue = "1", Category = "Sound" },
		{ Name = "Sound_EnableHardware", Type = "CVar", DefaultValue = "0", Category = "Sound" },
		{ Name = "Sound_EnableMusic", Type = "CVar", DefaultValue = "1", Category = "Sound" },
		{ Name = "Sound_EnablePetSounds", Type = "CVar", DefaultValue = "1", Category = "Sound" },
		{ Name = "Sound_EnableReverb", Type = "CVar", DefaultValue = "0", Category = "Sound" },
		{ Name = "Sound_EnableSFX", Type = "CVar", DefaultValue = "1", Category = "Sound" },
		{ Name = "Sound_EnableSoftwareHRTF", Type = "CVar", DefaultValue = "0", Category = "Sound" },
		{ Name = "Sound_EnableSoundWhenGameIsInBG", Type = "CVar", DefaultValue = "1", Category = "Sound" },
		{ Name = "Sound_ListenerAtCharacter", Type = "CVar", DefaultValue = "1", Category = "Sound" },
		{ Name = "Sound_MasterVolume", Type = "CVar", DefaultValue = "1.0", Category = "Sound" },
		{ Name = "Sound_MaxCacheableSizeInBytes", Type = "CVar", DefaultValue = "1048576", Category = "Sound" },
		{ Name = "Sound_MaxCacheSizeInBytes", Type = "CVar", DefaultValue = "16777216", Category = "Sound" },
		{ Name = "Sound_MusicVolume", Type = "CVar", DefaultValue = "0.4", Category = "Sound" },
		{ Name = "Sound_NumChannels", Type = "CVar", DefaultValue = "32", Category = "Sound" },
		{ Name = "Sound_OutputDriverIndex", Type = "CVar", DefaultValue = "0", Category = "Sound" },
		{ Name = "Sound_OutputDriverName", Type = "CVar", DefaultValue = "Primary Sound Driver", Category = "Sound" },
		{ Name = "Sound_OutputQuality", Type = "CVar", DefaultValue = "1", Category = "Sound" },
		{ Name = "Sound_SFXVolume", Type = "CVar", DefaultValue = "1.0", Category = "Sound" },
		{ Name = "Sound_VoiceChatInputDriverIndex", Type = "CVar", DefaultValue = "0", Category = "Sound" },
		{ Name = "Sound_VoiceChatInputDriverName", Type = "CVar", DefaultValue = "Primary Sound Capture Driver", Category = "Sound" },
		{ Name = "Sound_VoiceChatOutputDriverIndex", Type = "CVar", DefaultValue = "0", Category = "Sound" },
		{ Name = "Sound_VoiceChatOutputDriverName", Type = "CVar", DefaultValue = "Primary Sound Driver", Category = "Sound" },
		{ Name = "Sound_ZoneMusicNoDelay", Type = "CVar", DefaultValue = "0", Category = "Sound" },
		{ Name = "SoundMemoryCache", Type = "CVar", DefaultValue = "4", Category = "Sound" },
		{ Name = "spamFilter", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "specular", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "spellEffectLevel", Type = "CVar", DefaultValue = "9", Category = "General" },
		{ Name = "SplineOpt", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "StartTalkingDelay", Type = "CVar", DefaultValue = "0.0", Category = "General" },
		{ Name = "StartTalkingTime", Type = "CVar", DefaultValue = "1.0", Category = "General" },
		{ Name = "statusTextPercentage", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "stopAutoAttackOnTargetChange", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "StopTalkingDelay", Type = "CVar", DefaultValue = "0.0", Category = "General" },
		{ Name = "StopTalkingTime", Type = "CVar", DefaultValue = "2.0", Category = "General" },
		{ Name = "synchronizeBindings", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "synchronizeConfig", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "synchronizeMacros", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "synchronizeSettings", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "taintLog", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "talentFrameShown", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "targetOfTargetMode", Type = "CVar", DefaultValue = "5", Category = "General" },
		{ Name = "targetStatusText", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "terrainAlphaBitDepth", Type = "CVar", DefaultValue = "8", Category = "General" },
		{ Name = "texLodBias", Type = "CVar", DefaultValue = "0.0", Category = "General" },
		{ Name = "textureCacheSize", Type = "CVar", DefaultValue = "32", Category = "General" },
		{ Name = "textureFilteringMode", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "threatPlaySounds", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "threatShowNumeric", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "threatWarning", Type = "CVar", DefaultValue = "3", Category = "General" },
		{ Name = "threatWorldText", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "timeMgrAlarmEnabled", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "timeMgrAlarmMessage", Type = "CVar", DefaultValue = "", Category = "General" },
		{ Name = "timeMgrAlarmTime", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "timeMgrUseLocalTime", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "timeMgrUseMilitaryTime", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "trackedAchievements", Type = "CVar", DefaultValue = "", Category = "General" },
		{ Name = "trackedQuests", Type = "CVar", DefaultValue = "", Category = "General" },
		{ Name = "trackerFilter", Type = "CVar", DefaultValue = "7", Category = "General" },
		{ Name = "trackerSorting", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "UberTooltips", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "UIFaster", Type = "CVar", DefaultValue = "3", Category = "Interface" },
		{ Name = "uiScale", Type = "CVar", DefaultValue = "1.0", Category = "Interface" },
		{ Name = "unitHighlights", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "UnitNameEnemyGuardianName", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "UnitNameEnemyPetName", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "UnitNameEnemyPlayerName", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "UnitNameEnemyTotemName", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "UnitNameFriendlyGuardianName", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "UnitNameFriendlyPetName", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "UnitNameFriendlyPlayerName", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "UnitNameFriendlyTotemName", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "UnitNameNonCombatCreatureName", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "UnitNameNPC", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "UnitNameOwn", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "UnitNamePlayerGuild", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "UnitNamePlayerPVPTitle", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "useDesktopMouseSpeed", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "useEnglishAudio", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "UseNVShaders", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "UsePboSubImage", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "UsePboSubImageZeroOffset", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "useSimpleChat", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "useUiScale", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "useWeatherShaders", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "videoOptionsVersion", Type = "CVar", DefaultValue = "0", Category = "Graphics" },
		{ Name = "violenceLevel", Type = "CVar", DefaultValue = "2", Category = "General" },
		{ Name = "VoiceActivationSensitivity", Type = "CVar", DefaultValue = "0.4", Category = "General" },
		{ Name = "VoiceChatMode", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "VoiceChatSelfMute", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "watchFrameBaseAlpha", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "watchFrameIgnoreCursor", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "watchFrameState", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "watchFrameWidth", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "waterLOD", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "weatherDensity", Type = "CVar", DefaultValue = "2", Category = "General" },
		{ Name = "widescreen", Type = "CVar", DefaultValue = "1", Category = "General" },
		{ Name = "windowResizeLock", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "worldMapOpacity", Type = "CVar", DefaultValue = "0", Category = "General" },
		{ Name = "worldPoolUsage", Type = "CVar", DefaultValue = "Dynamic", Category = "General" },
		{ Name = "xpBarText", Type = "CVar", DefaultValue = "0", Category = "General" },
	},

	Events =
	{
		{
			Name = "CvarUpdate",
			Type = "Event",
			LiteralName = "CVAR_UPDATE",
			Payload =
			{
				{ Name = "glStr", Type = "string", Nilable = false },
				{ Name = "value", Type = "string", Nilable = false },
			},
		},
	},

	Tables =
	{
	},
};

APIDocumentation:AddDocumentationTable(Cvar);
